#!/usr/bin/env bash
# Script to display information about subdomains

subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    
    local line
    line=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    
    echo "${subdomain} ${line}" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ]; then
    subdomain_info "$1" "www"
    subdomain_info "$1" "lb-01"
    subdomain_info "$1" "web-01"
    subdomain_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    subdomain_info "$1" "$2"
fi
