#!/usr/bin/env bash
# Installs Nginx

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
sudo /etc/init.d/nginx start
