#!/usr/bin/env bash
# Installs Nginx

ssh ubuntu@52.3.220.70
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
