#!/usr/bin/env bash                                                                          
# Configure your Nginx server so that
# /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i 's|listen \[::\]:80 default_server;|listen \[::\]:80 default_server;\
	location /redirect_me {\
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
	}|' /etc/nginx/sites-enabled/default
sudo service nginx start
