#!/usr/bin/env bash                                                                          
# Configure your Nginx server so that
# /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
