#!/usr/bin/env bash
# Installs nginx web server

REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
PG_NOTFOUND="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
error="#error_page 404 /404.html;"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@$error@$PG_NOTFOUND@" /etc/nginx/sites-available/default

sudo service nginx restart
