#!/usr/bin/env bash
# Thuis script Installs and configures HAproxy on your lb-01 server.


CONFGF="\\\nlisten appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 275247-web-01 52.3.220.70 check\n\tserver 275247-web-02 54.159.2.25 check\n"

sudo apt-get update
sudo apt-get -y install nginx
sudo apt-get install -y haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo sed -i "\$a $CONFGF" /etc/haproxy/haproxy.cfg

sudo service haproxy start
