#!/usr/bin/env bash
# The script displays Best School 10 times
# but for the 9th iteration, displays Best School and then Hi on a new line.
count=1
while [ $count -le 20 ]
do
	case $count in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		*) echo "$count"
	esac
	((count++))
done
