#!/usr/bin/env bash
# The script displays Best School 10 times using while loop
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		((minutes++))
	done
	((hour++))
done
