#!/usr/bin/env bash
# The script configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# Check if the script is running with root privileges
if [ "$(id -u)" -ne 0 ]
then
	exit 1
fi

cp /etc/hosts /etc/hosts.bak

# Modify the hosts file to add the required mappings
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
