#!/usr/bin/env bash
# This script runs Nginx as Nginx

# Check if Nginx is already installed; if not, install it
if ! command -v nginx &> /dev/null; then
    echo "Nginx is not installed. Installing..."
    apk add --no-cache nginx
fi

sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080 default_server;/g' /etc/nginx/conf.d/default.conf
sudo -u nginx service nginx restart
