#!/usr/bin/env bash
# This script runs Nginx as Nginx

sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080 default_server;/g' /etc/apache2/ports.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -1 apache2
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
